development:
  password: ${DEV_SHOPIFY_PASSWORD}
  theme_id: "${DEV_SHOPIFY_THEME_ID}"
  store: ${DEV_SHOPIFY_STORE_URL}
staging:
  password: ${SHOPIFY_PASSWORD}
  theme_id: "${SHOPIFY_THEME_ID}"
  store: ${SHOPIFY_STORE_URL}
production:
  password: ${SHOPIFY_PASSWORD}
  theme_id: "${SHOPIFY_THEME_ID}"
  store: ${SHOPIFY_STORE_URL}